INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Maldives', 'Description: Known for its pristine white sandy beaches, crystal-clear turquoise waters, and luxurious resorts, the Maldives is a tropical paradise ideal for relaxation, snorkeling, and scuba diving.', '18/08/2023', '27/08/2023', '1145', 'https://images.thrillophilia.com/image/upload/s--vI0Q6HT9--/c_fill,g_auto,h_600,q_auto,w_975/f_auto,fl_strip_profile/v1/images/photos/000/082/497/original/1675261154_shutterstock_2148766633.jpg.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Santorini, Greece', 'Description: Famous for its iconic blue-domed churches, whitewashed buildings, and stunning sunsets, Santorini offers breathtaking views, beautiful beaches, and a rich history.', '26/09/2023', '2/10/2023', '976', 'https://www.savoredjourneys.com/wp-content/uploads/2018/03/8-things-to-do-in-santorini-feature.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Bora Bora, French Polynesia', 'Description: Bora Bora is renowned for its stunning overwater bungalows, vibrant coral reefs, and turquoise lagoons. It\'s a popular destination for honeymooners and water sports enthusiasts.', '15/082023', '22/08/2023', '1205', 'https://www.wendyperrin.com/wp-content/uploads/2020/11/Bora-Bora-French-Polynesia-dock-and-bungalow-shutterstock_361041146-1000x667.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Machu Picchu, Peru:', 'Description: Machu Picchu is an ancient Incan city perched high in the mountains. It offers incredible archaeological ruins, breathtaking mountain scenery, and opportunities for hiking the Inca Trail.', '25/07/2023', '31/07/2023', '1312', 'https://cloudfront-ap-southeast-2.images.arcpublishing.com/nzme/43WWON3AZEMRDTRF7NWDOTXIPY.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Serengeti National Park, Tanzania', 'Description: Serengeti National Park is famous for its vast savannahs, incredible wildlife, and the Great Migration of wildebeest and zebras. It\'s a top safari destination.', '6/10/2023', '13/10/2023', '1950', 'https://www.serengeti.com/assets/img/serengeti-national-park.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Great Barrier Reef, Australia', 'Description: The Great Barrier Reef is the world\'s largest coral reef system, teeming with diverse marine life. It offers excellent snorkeling, scuba diving, and boat tours.', '15/12/2023', '20/12/2023', '1433', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0f/36/f1/32.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Kyoto, Japan', 'Description: Kyoto is a city known for its traditional temples, stunning gardens, and preserved historical districts. It\'s a hub of Japanese culture, arts, and traditions.', '13/07/2023', '19/07/2023', '1865', 'https://tourscanner.com/blog/wp-content/uploads/2022/09/things-to-do-in-Kyoto.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Reykjavik, Iceland', 'Description: Reykjavik, the capital of Iceland, offers a unique blend of natural wonders and a vibrant city life. It\'s known for its geothermal spas, stunning landscapes, and Northern Lights.', '02/08/2023', '12/08/2023', '1328', 'https://www.thoughtco.com/thmb/qHQluwOCpde3AbIgv4qT9O6XhcU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-158525984-5b6df57dc9e77c005086b0ca.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Rio de Janeiro, Brazil', 'Description: Rio de Janeiro is famous for its iconic landmarks like Christ the Redeemer and Copacabana Beach. It offers a vibrant nightlife, rich culture, and lively samba music and dance.', '28/12/2023', '05/01/2024', '1422', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Cidade_Maravilhosa.jpg/1200px-Cidade_Maravilhosa.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Dubai, United Arab Emirates', 'Description: Dubai is a modern metropolis known for its impressive skyscrapers, luxury shopping malls, artificial islands, and desert safaris. It\'s a city of luxury and innovation.', '17/11/2023', '23/11/2023', '2128', 'https://a.cdn-hotels.com/gdcs/production121/d772/6b5a9a4c-fd06-4bcf-b2f0-d979e3704cf9.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Queenstown, New Zealand', 'Description: Queenstown is an adventure capital, surrounded by stunning mountains, lakes, and fjords. It offers activities like bungee jumping, skiing, hiking, and jet boating.', '02/08/2023', '11/08/2023', '998', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Queenstown_1_%288168013172%29.jpg');
INSERT INTO `vacation_sql`.`destination` (`destination`, `description`, `begin`, `finish`, `price`, `img`) VALUES ('Barcelona, Spain', 'Description: Barcelona is a vibrant city known for its unique architecture, including the famous Sagrada Familia and Park Güell. It offers a lively atmosphere, beautiful beaches, and delicious cuisine.', '04/09/2023', '11/09/2023', '1632', 'https://res.cloudinary.com/sagacity/image/upload/c_crop,h_770,w_1000,x_0,y_0/c_limit,f_auto,fl_lossy,q_80,w_1080/shutterstock_174454670_gicbgy.jpg');

=================================================================================
UPDATE `vacation_sql`.`destination` SET `destination` = 'checking addVac2', `description` = 'Description: Famous for its iconic blue-domed churches, whitewashed buildings, and stunning sunsets, Santorini offers breathtaking views, beautiful beaches, and a rich 2history.', `begin` = '26/09/20223', `finish` = '2/10/22023', `price` = '926', `img` = 'https://www.savoredjourneys.com/wp-content/uploads/2018/03/28-things-to-do-in-santorini-feature.jpg' WHERE (`id` = '14');


INSERT INTO `vacation_sql`.`likes` (`user_id`, `vac_id`) VALUES ('3', '18');